
node {
	stage 'Checkout'
		checkout scm

	stage 'Build'
		sh 'nuget restore SolutionName.sln'
		sh "\"${tool 'MSBuild'}\"myapp/myapp.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"

	stage 'Archive'
		archive 'myapp/bin/Release/**'

}
