pipeline
{
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                echo 'myapp/myapp.csproj'
                echo 'i love programing'
                echo "today is $(date)"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
